### ISSUE TITLE
allow give pod version from command line when update

### ISSUE THREAD

**Issue by n0rad** [blablacar/green-garden#11]

**Comment by n0rad** [comment]
@MattKetmo update the system config file locally may be easier ? especially since it's a list.
we can revert it locally just after maybe ?

**Comment by MattKetmo** [comment]
Yes, I can also use the template-like system I'm already using for pod & aci (`cnt-manifest.tmpl.yml`).

**Comment by n0rad** [comment]
done in v59 by supporting templating on manifest
